### ISSUE TITLE
Not an issue, more of an inquiry

### ISSUE THREAD

**Issue by Masamune3210** [thankjura/ds4battery#1]
While I know that this is literally named after the DS4, would this be able to support the DS3 as well? As far as I know, the DS3 and the DS4 dont handle that many things differently other than paring

**Comment by thankjura** [comment]
If ds3 provides information to the sysfs then it should work.
I do not have a ds3 to check

**Comment by Masamune3210** [comment]
If you can tell me what to do, i can run anything that you need to see if it does, that or i could just let you connect to my computer and do it yourself if you want

**Comment by thankjura** [comment]
https://extensions.gnome.org/extension/1283/dual-shock-4-battery-percentage/

Ds3 must

**Comment by thankjura** [comment]
https://extensions.gnome.org/extension/1283/dual-shock-4-battery-percentage/

Ds3 should work

**Comment by Masamune3210** [comment]
Seems to work perfectly fine!
![screenshot from 2017-09-03 10-18-44](https://user-images.githubusercontent.com/1053504/30004248-50c98b72-9091-11e7-9d9c-c96c619663d7.png)
