### ISSUE TITLE
[Porting required] Gnome 45 changed from GJS to ESM

### ISSUE THREAD

**Issue by onlyreportingissues** [thankjura/ds4battery#15]
https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

Helpful link above. The Gnome devs offer additional help on their [Discourse](https://discourse.gnome.org/tag/extensions) and [Matrix](https://matrix.to/#/#extensions:gnome.org) channels, if needed.

**Comment by thankjura** [comment]
Done
