### ISSUE TITLE
Multiple Controllers

### ISSUE THREAD

**Issue by ElectricPrism** [thankjura/ds4battery#2]
I use 4 DS4 controllers and as wondering if battery indicator for multiple controllers is in or is possible, thanks.

**Comment by thankjura** [comment]
Сan you try the latest version from master? 
I have only one gamepad and I can not check

**Comment by ElectricPrism** [comment]
I tried the latest version.

It only has one icon in the system tray.

If I disconnect the device that appears in the system tray it auto-cycles and displays the battery of the next device.

```
➜  power_supply ls -la /sys/class/power_supply/
total 0
drwxr-xr-x  2 root root 0 May 28 17:10 .
drwxr-xr-x 63 root root 0 May 28 17:10 ..
lrwxrwxrwx  1 root root 0 May 28 17:27 sony_controller_battery_1c:66:6d:e2:19:47 -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.3/1-2.3:1.0/0003:054C:05C4.0012/power_supply/sony_controller_battery_1c:66:6d:e2:19:47
lrwxrwxrwx  1 root root 0 May 28 17:34 sony_controller_battery_40:1b:5f:3d:25:dd -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.2/1-2.2:1.0/bluetooth/hci0/hci0:11/0005:054C:05C4.0018/power_supply/sony_controller_battery_40:1b:5f:3d:25:dd
lrwxrwxrwx  1 root root 0 May 28 17:32 sony_controller_battery_40:1b:5f:9a:04:93 -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/bluetooth/hci1/hci1:1/0005:054C:05C4.0017/power_supply/sony_controller_battery_40:1b:5f:9a:04:93
```

That's the CLI controller output incase it's helpful. I also have the devices listed here:

```
/dev/input/js0
/dev/input/js1
/dev/input/js2
/dev/input/js3
```

**Comment by thankjura** [comment]
I rewrote the extension, try now

**Comment by ElectricPrism** [comment]
![test ds4battery](https://user-images.githubusercontent.com/635971/40685058-0d8eee26-6348-11e8-8e5d-263889f687da.gif)

(Sorry about the quality, github wont allow me to post a webm screencast without converting  to gif)

This is using 4x USB cables.

It's pretty cool that it has a controller color above the icon now.

It looks like it's working, theoretically there could be more than 4 controllers but I guess it's unlikely.

The only other thing that could be improved is probably the battery notification showing up as a blank grey box with no text.

I can't recall any instance of plugging in an input device that generates a notification.

I guess sometimes devices that have a rechargeable battery trigger a notification such-as a cellphone.

Thanks! :+1:
