### ISSUE TITLE
[object GjsModule byteArray]%

### ISSUE THREAD

**Issue by sneakingJ** [thankjura/ds4battery#4]
Recently it doesn't show me the percentage number anymore but instead the text in the title.

**Comment by cp-jonas** [comment]
Maybe it's this problem: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/520

**Comment by sneakingJ** [comment]
Maybe it's this problem: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/520

**Comment by sneakingJ** [comment]
I applied the fix locally and it works. You just have to add some lines to the readFile function:
```
function readFile(deviceId, fileName) {
    let filePath = GLib.build_filenamev([POWER_DIR_PATH, DEVICE_PREFIX + deviceId, fileName]);
    let file = Gio.File.new_for_path(filePath);
    let out = file.load_contents(null);
    let value = out[1];
    if (value) {
        if (!ByteArray.toString(value).match(/GjsModule byteArray/)) {
            return ByteArray.toString(value).replace("\n", "");
        }
        return parseInt(value);
    }

    return "";
}
```

**Comment by thankjura** [comment]
Hmm. What your gnome-shell version?

**Comment by sneakingJ** [comment]
> Hmm. What your gnome-shell version?

GNOME Shell 3.28.4
